name: bookswap
description: A small textbook swap marketplace for students.
publish_to: 'none'


environment:
sdk: '>=2.18.0 <4.0.0'


dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.5
provider: ^6.0.5


# Firebase
firebase_core: ^2.10.0
firebase_auth: ^4.6.0
cloud_firestore: ^4.7.0
firebase_storage: ^11.1.0


# Utilities
uuid: ^3.0.7
image_picker: ^0.8.7+4


dev_dependencies:
flutter_test:
sdk: flutter


flutter:
uses-material-design: true
assets:
- assets/placeholder.png